# Generated by Django 2.1.5 on 2019-01-22 20:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Comming Soon..', max_length=60, null=True)),
                ('logo_url', models.ImageField(blank=True, null=True, upload_to='images/events/')),
                ('background_url', models.ImageField(blank=True, null=True, upload_to='images/events/')),
                ('offical_link', models.CharField(blank=True, default='https://', max_length=200, null=True)),
                ('color_class', models.CharField(choices=[('color-yellow', 'color-yellow'), ('color-blue', 'color-blue'), ('color-voilet', 'color-voilet'), ('color-grey', 'color-grey')], default='color-yellow', max_length=10)),
                ('video_link', models.CharField(blank=True, default='https://', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='main.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('achievement', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/events/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='main.Event')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('has_email_verified', models.BooleanField(default=False)),
                ('verification_key', models.CharField(max_length=40)),
                ('image', models.ImageField(null=True, upload_to='images/members/')),
                ('university_roll', models.CharField(max_length=15, null=True)),
                ('std_no', models.CharField(max_length=15, null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
                ('section', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=0, null=True)),
                ('fb_link', models.CharField(max_length=50, null=True)),
                ('li_link', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=20, null=True)),
                ('membership_id', models.CharField(max_length=20, null=True)),
                ('year', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')], default=0, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10, null=True)),
                ('address', models.TextField(null=True)),
                ('phn_no', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('venue', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('logo_url', models.ImageField(null=True, upload_to='images/workshops/')),
                ('background_url', models.ImageField(null=True, upload_to='images/workshops/')),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=400)),
                ('reg_start_date', models.DateField(null=True)),
                ('reg_end_date', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('reg_status', models.BooleanField(default=False)),
                ('status', models.CharField(default='Comming Soon..', max_length=60)),
                ('wall_status', models.BooleanField(default=False)),
                ('theme_color', models.CharField(default='#84859d', max_length=10)),
                ('video_link', models.CharField(default='https://', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopFaqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='main.Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopOrganiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisers', to='main.Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('university_roll', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')], default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('phn_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_limit', models.IntegerField(default=1)),
                ('details', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=1)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='main.Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('tech', models.CharField(max_length=200, unique=True)),
                ('details', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='images/workshops/projects/')),
                ('video_link', models.CharField(default='https://', max_length=200)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=130)),
                ('team_name', models.CharField(max_length=50)),
                ('ref_code', models.CharField(blank=True, default='no', max_length=20, null=True)),
                ('enroll_date', models.DateField(default=django.utils.timezone.now, editable=False, null=True)),
                ('is_team_local', models.BooleanField(default=True)),
                ('enroll_status', models.BooleanField(default=False)),
                ('leader_email', models.EmailField(max_length=254)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WorkshopPlan')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Workshop')),
            ],
        ),
        migrations.AddField(
            model_name='workshopparticipant',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.WorkshopRegistration'),
        ),
    ]
