# Generated by Django 2.1.4 on 2019-01-04 13:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_created', models.DateTimeField(auto_now_add=True)),
                ('timestamp_updated', models.DateTimeField(auto_now=True)),
                ('has_email_verified', models.BooleanField(default=False)),
                ('verification_key', models.CharField(max_length=40)),
                ('image', models.ImageField(null=True, upload_to='images/members/')),
                ('fathers_name', models.CharField(max_length=50, null=True)),
                ('university_roll', models.CharField(max_length=15, null=True)),
                ('branch', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=20, null=True)),
                ('membership_id', models.CharField(max_length=20, null=True)),
                ('year', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')], default=0, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10, null=True)),
                ('aadhar_no', models.CharField(max_length=16, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 16', regex='^.{12}$')])),
                ('phn_no', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user profile',
                'verbose_name_plural': 'user profiles',
            },
        ),
    ]
