# Generated by Django 2.1.5 on 2019-01-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistration',
            name='payment_by',
            field=models.CharField(blank=True, default='Not Yet', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='background_url',
            field=models.CharField(default='https://', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo_url',
            field=models.CharField(default='https://', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventtimeline',
            name='image',
            field=models.CharField(default='https://', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.CharField(default='https://', max_length=200),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='background_url',
            field=models.CharField(default='https://', max_length=200),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='logo_url',
            field=models.CharField(default='https://', max_length=200),
        ),
        migrations.AlterField(
            model_name='workshopproject',
            name='img',
            field=models.CharField(default='https://', max_length=200),
        ),
    ]
