# Generated by Django 2.1.4 on 2019-01-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190104_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='aadhar_no',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fathers_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='std_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
