# Generated by Django 2.1.5 on 2019-02-21 21:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190123_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='AacarRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('university_roll', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')], default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('phn_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('enroll_status', models.BooleanField(default=False)),
                ('enroll_date', models.DateField(default=django.utils.timezone.now, editable=False, null=True)),
                ('payment_by', models.CharField(blank=True, default='Not Yet', max_length=50, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
