# Generated by Django 2.1.4 on 2019-01-04 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20190104_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(default='Comming Soon..', max_length=60)),
                ('logo_url', models.ImageField(null=True, upload_to='images/events/')),
                ('background_url', models.ImageField(null=True, upload_to='images/events/')),
                ('offical_link', models.CharField(default='https://', max_length=200)),
                ('theme_color', models.CharField(default='#84859d', max_length=10)),
                ('short_description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('achievement', models.CharField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('venue', models.CharField(max_length=50)),
                ('logo_url', models.ImageField(null=True, upload_to='images/workshops/')),
                ('background_url', models.ImageField(null=True, upload_to='images/workshops/')),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=400)),
                ('reg_start_date', models.DateField(null=True)),
                ('reg_end_date', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('reg_status', models.BooleanField(default=False)),
                ('status', models.CharField(default='Comming Soon..', max_length=60)),
                ('wall_status', models.BooleanField(default=False)),
                ('theme_color', models.CharField(default='#84859d', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopFaqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopOrganiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_limit', models.IntegerField(default=1)),
                ('details', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=1)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Workshop')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('tech', models.CharField(max_length=200, unique=True)),
                ('details', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='images/workshops/projects/')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Workshop')),
            ],
        ),
    ]
