# Generated by Django 2.1.4 on 2019-01-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_event_eventteam_eventtimeline_workshop_workshopfaqs_workshoporganiser_workshopplan_workshopproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_link',
            field=models.CharField(default='https://', max_length=200),
        ),
        migrations.AddField(
            model_name='workshop',
            name='video_link',
            field=models.CharField(default='https://', max_length=200),
        ),
        migrations.AddField(
            model_name='workshopproject',
            name='video_link',
            field=models.CharField(default='https://', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventteam',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='main.Event'),
        ),
        migrations.AlterField(
            model_name='eventtimeline',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='main.Event'),
        ),
        migrations.AlterField(
            model_name='workshopfaqs',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='main.Workshop'),
        ),
        migrations.AlterField(
            model_name='workshoporganiser',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisers', to='main.Workshop'),
        ),
        migrations.AlterField(
            model_name='workshopplan',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='main.Workshop'),
        ),
        migrations.AlterField(
            model_name='workshopproject',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.Workshop'),
        ),
    ]
