# Generated by Django 2.1.4 on 2019-01-04 17:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190104_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('university_roll', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.IntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th')], default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('phn_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=130)),
                ('team_name', models.CharField(max_length=50)),
                ('ref_code', models.CharField(default='no', max_length=20, null=True)),
                ('enroll_date', models.DateField(default=django.utils.timezone.now, editable=False, null=True)),
                ('is_team_local', models.BooleanField(default=True)),
                ('enroll_status', models.BooleanField(default=False)),
                ('leader_email', models.EmailField(max_length=254)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.WorkshopPlan')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Workshop')),
            ],
        ),
        migrations.AddField(
            model_name='workshopparticipant',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='main.WorkshopRegistration'),
        ),
    ]
