# Generated by Django 2.1.5 on 2019-01-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190104_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.CharField(default='innovacion', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='slug',
            field=models.CharField(default='innovacion', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
