# Generated by Django 2.1.5 on 2019-01-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190116_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='theme_color',
        ),
        migrations.AddField(
            model_name='event',
            name='bg_color',
            field=models.CharField(default='#84859d', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='bg_color_light',
            field=models.CharField(default='#84859d', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='box_shadow_color',
            field=models.CharField(default='#84859d', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='text_color_hover',
            field=models.CharField(default='#84859d', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='background_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='offical_link',
            field=models.CharField(blank=True, default='https://', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, default='Comming Soon..', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_link',
            field=models.CharField(blank=True, default='https://', max_length=200, null=True),
        ),
    ]
