# Generated by Django 2.1.5 on 2019-01-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190119_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bg_color_light',
        ),
        migrations.RemoveField(
            model_name='event',
            name='box_shadow_color',
        ),
        migrations.RemoveField(
            model_name='event',
            name='text_color_hover',
        ),
        migrations.AddField(
            model_name='event',
            name='color_class',
            field=models.CharField(choices=[('color-yellow', 'color-yellow'), ('color-blue', 'color-blue'), ('color-voilet', 'color-voilet'), ('color-grey', 'color-grey')], default='color-yellow', max_length=10),
        ),
        migrations.AddField(
            model_name='eventtimeline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/events/'),
        ),
    ]
