# Generated by Django 2.1.5 on 2019-01-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190121_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopregistration',
            name='ref_code',
            field=models.CharField(blank=True, default='no', max_length=20, null=True),
        ),
    ]
